#!/bin/bash -ex
exec>>(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
#Install & Configure Docker
yum install -y wget vim net-tools initscripts gcc make tar bind-utils nc git unzip
systemctl stop postfix.service
systemctl disable postfix.service
# Install required system packages.
yum install -y yum-utils device-mapper-persistent-data lvm2 tree
# Add Docker repository to package manager source list. 
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
#Install Docker packages from repository.
yum install -y docker-ce docker-ce-cli containerd.io
#Modify Docker daemon configuration.
mkdir /etc/docker
cat <<EOF> /etc/docker/daemon.json
"exec-opts": ["native.cgroupdriver-systemd"], "max-size":"100"
"log-driver":"json-file",
"log-opts": {
"storage-driver": "overlay2",
"storage-opts": [
"overlay2.override_kernel_check-true"
EOF
#Apply configuration changes to Docker service by restarting it.
systemctl restart docker.service
# Check status of Docker service. 
systemctl status docker.service
# Enable Docker service at boot. 
systemctl enable docker.service
#Install Kubernetes
# Set SELinux in permissive mode.
sudo setenforce 0
sudo sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
#Permanently disable Linux swap memory. swapoff -a
cat <<EOF > /etc/fstab #/swapfile none swap defaults 0 0 -EOF I
# Permanently set required network and swap Linux kernel params.
 Ecat <<EOF> /etc/sysctl.d/k8s.conf
vm.swappiness=0
net.bridge.bridge-nf-call-ip6tables - 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-iptables - 1
EOF
#Apply required network and swap Linux kernel params. 
sudo sysctl --system
#Add Kubernetes repository to package manager source list.
cat <<EOF> /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name-Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch enabled-1
gpgcheck=0
repo_gpgcheck-0
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl I
EOF
# Install Kubernetes packages from repository.
yum install -y kubelet-1.19.4 kubeadm-1.19.4 kubect1-1.19.4 --disableexcludes kubernetes
#Install Git.
yum install git 
git clone https://github.com/lskiranch/kickstart-kubernetes.qit /opt/kickstart-kubernetes
chown -R centos: centos /opt/kickstart-kubernetes 
git clone https://github.com/lskiranch/kickstart-flask.git /opt/kickstart-kubernetes/app
