#!/bin/bash -ex
exec>>(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
#------------Install & Configure Docker ---------------------
yum install -y wget vim net-tools initscripts gcc make tar bind-utils nc git unzip
systemctl stop postfix.service
systemctl disable postfix.service
# Install required system packages.
yum install -y yum-utils device-mapper-persistent-data lvm2 tree
# Add Docker repository to package manager source list. 
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
#Install Docker packages from repository.
yum install -y docker-ce docker-ce-cli containerd.io
#Modify Docker daemon configuration.
mkdir /etc/docker
cat <<EOF> /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"], 
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100"
  },
  "storage-driver": "overlay2",
  "storage-opts": [
    "overlay2.override_kernel_check=true"
  ]
}
EOF
#Apply configuration changes to Docker service by restarting it.
systemctl restart docker.service
# Check status of Docker service. 
systemctl status docker.service
# Enable Docker service at boot. 
systemctl enable docker.service
#---------------Install Kubernetes ------------------------------------
# Set SELinux in permissive mode.
sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
#Permanently disable Linux swap memory.
 sudo swapoff -a
 cat <<EOF > /etc/fstab
 #/swapfile none swap defaults 0 0 
EOF
#Permanently set required network and swap Linux kernel params.
cat <<EOF > /etc/sysctl.d/k8s.conf
vm.swappiness=0
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
#Apply required network and swap Linux kernel params. 
sudo sysctl --system
#Add Kubernetes repository to package manager source list.
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
# Install Kubernetes packages from repository.
yum install -y kubelet-1.19.4 kubeadm-1.19.4 kubect1-1.19.4 --disableexcludes=kubernetes
#Install Git.
yum install git 
git clone https://github.com/bvenkydevops/kickstart-kubernetes.git /opt/kickstart-kubernetes
chown -R centos:centos /opt/kickstart-kubernetes 
git clone https://github.com/bvenkydevops/flask.git /opt/kickstart-kubernetes/app
